### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by burtbeckwith**
Minor changes and cleanup. You don't want to add yourself to the "developers" property since you're already listed as one with the author and authorEmail properties, otherwise you'll be listed twice in the POM file.

Also please drop the minimum Grails version from 2.1 to 2.0. I see that the underscore plugin requires 2.1+ but this is also an artificially high minimum, so I've sent a pull request for that plugin. If the author accepts it and releases a new version, please consider fixing yours, unless you really do want to exclude a lot of potential users :)

### CODE REVIEW

**Comment by groovydev** [comment]
You're right. I've dropped the minimum Grails version from 2.1 to 2.0.

**Comment by burtbeckwith** [comment]
Cool - it won't work in 2.0 apps until the underscore plugin is updated though - you might want to add that to the readme (or restore your 2.1 restriction and re-release with that change when his is updated).

**Comment by groovydev** [comment]
Ok. I restore 2.1 restriction and will drop it when underscore plugin would be updated.

**Comment by burtbeckwith** [comment]
FYI the underscore plugin was just updated to version 1.4.2 and supports 2.0+

**Comment by groovydev** [comment]
Updated and published.

**Pull request merged**
